-- Criar a tabela de contatos
CREATE TABLE contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Criar índices para melhor performance
CREATE INDEX idx_contatos_email ON contatos(email);
CREATE INDEX idx_contatos_created_at ON contatos(created_at);

-- Adicionar comentários na tabela
COMMENT ON TABLE contatos IS 'Tabela para armazenar informações de contato dos usuários';
COMMENT ON COLUMN contatos.id IS 'Identificador único do contato';
COMMENT ON COLUMN contatos.nome IS 'Nome completo do contato';
COMMENT ON COLUMN contatos.email IS 'Email do contato';
COMMENT ON COLUMN contatos.telefone IS 'Número de telefone do contato';
COMMENT ON COLUMN contatos.created_at IS 'Data e hora de criação do registro';

-- Configurar políticas de segurança (RLS)
ALTER TABLE contatos ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir inserção anônima
CREATE POLICY "Permitir inserção anônima" ON contatos
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Criar política para permitir leitura anônima
CREATE POLICY "Permitir leitura anônima" ON contatos
    FOR SELECT
    TO anon
    USING (true); 